
/****** Create a New Database "RMS" ******/
/****** Script perpared by : Abdul Halim****/

USE [master]
GO
CREATE DATABASE [RMS]; 

GO
ALTER DATABASE [RMS] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [RMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RMS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RMS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RMS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RMS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RMS] SET  MULTI_USER 
GO
ALTER DATABASE [RMS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RMS] SET DB_CHAINING OFF 
GO


/***Create necessary tables  for RMS database***/

GO
USE [RMS]
GO

/***Create tables  [dbo].[Patient] for RMS database***/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patient](
	[PatientId] [int] IDENTITY(1,1) NOT NULL,
	[HSN] [varchar](50) NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NULL,
	[DOB] [smalldatetime] NULL,
	[Address] [varchar](50) NULL,
	[City] [varchar](20) NULL,
	[Province] [varchar](20) NULL,
	[ModifiedBy] [varchar](50) NULL,
	[ModifiedDate] [smalldatetime] NULL,
 CONSTRAINT [PK__Patient__970EC36612D06504] PRIMARY KEY CLUSTERED 
(
	[PatientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/***Create  table [dbo].[Provider]  for RMS database***/  
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Provider](
	[ProviderId] [int] IDENTITY(1,1) NOT NULL,
	[SpecialtyId] [int] NOT NULL,
	[IdentifierNo] [nchar](10) NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Address] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[Province] [varchar](50) NULL,
	[IsTakingNewPatient] [bit] NOT NULL,
	[LatestAvailabilityDate] [smalldatetime] NULL,
	[ModifiedBy] [varchar](50) NULL,
	[ModifiedDate] [smalldatetime] NULL,
 CONSTRAINT [PK__Provider__B54C687DB40D9B9D] PRIMARY KEY CLUSTERED 
(
	[ProviderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/***Create  table [dbo].[Provider]  for RMS database***/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Referral](
	[ReferralId] [int] IDENTITY(1,1) NOT NULL,
	[PatientId] [int] NOT NULL,
	[ProviderId] [int] NULL,
	[SpecialtyId] [int] NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[CreatedDate] [smalldatetime] NOT NULL,
	[ModifiedBy] [varchar](50) NULL,
	[ModifiedDate] [smalldatetime] NULL,
 CONSTRAINT [PK__Referral__A2C4A96616341B1D] PRIMARY KEY CLUSTERED 
(
	[ReferralId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/***Create  table [dbo].[Specialty]  for RMS database***/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Specialty](
	[SpecialtyId] [int] IDENTITY(1,1) NOT NULL,
	[SpecialtyName] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NULL,
	[ModifiedDate] [smalldatetime] NULL,
 CONSTRAINT [PK__Specialt__D768F6A8FA0CD52C] PRIMARY KEY CLUSTERED 
(
	[SpecialtyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RMS] SET  READ_WRITE 
GO


